# Generated by Django 3.1.2 on 2020-10-10 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_event_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_from',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_to',
            field=models.DateField(),
        ),
    ]
