# Generated by Django 3.1.2 on 2020-10-17 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201017_0939'),
        ('core', '0003_auto_20201017_1106'),
    ]

    operations = [
    ]
