# Generated by Django 3.1.2 on 2020-10-18 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201018_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='opinion',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
