# Generated by Django 3.1.2 on 2020-10-18 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_comment_opinion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='opinion',
            field=models.IntegerField(null=True),
        ),
    ]
